### ISSUE TITLE
运行报错 空指针

### ISSUE THREAD

**Issue by willamblack** [zhutougg/ZSXQFileDownload#1]
Exception in thread "main" java.lang.NullPointerException
        at com.zhutougg.zsxq.App.getFileIdList(App.java:65)
        at com.zhutougg.zsxq.App.main(App.java:48)

**Comment by zhutougg** [comment]
java -jar xxx.jar zsxq_access_token 圈子ID 文件存放路径
zsxq_access_token:在cookie中找
圈子ID：网页打开某个圈子时，URL中会有ID

**Comment by willamblack** [comment]
```
java -jar C:/Users/ZHANG/Desktop/ZSXQ.jar D7ACD380-8232-7D3B-ES52-BA8D74DAC684 1824528822 C:/zsxq/
Exception in thread "main" java.lang.NullPointerException
        at com.zhutougg.zsxq.App.getFileIdList(App.java:65)
        at com.zhutougg.zsxq.App.main(App.java:48)
```
不好意思，之前没有说清楚，我不懂Java，见谅。
是搭建了Java的运行环境后，下载了releases的jar文件。
然后改名为zsxq.jar
通过【java -jar zxsq.jar D7ACD380-8232-7D3B-ES52-BA8D74DAC684 1824528822 C:/zsxq/】这种命令来运行，报错。

**Comment by willamblack** [comment]
测试多次，一运行命令，知识星球网页版的就退出了。
但用其他脚本来批量采集文字内容，不会退出。
